export type { IPost } from './IPost'
export type { ICommentedPost } from './ICommentedPost'
export type { IAction } from './IAction'
export type { IThunkAction } from './IThunkAction'
export type { IAppState } from './IAppState'
